name: build
run-name: ${{ github.actor }} ğŸš€
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*-release" # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 6.10.0

      - run: |
          pnpm install
          pnpm run build:win

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: update.
          draft: false
          prerelease: false
          files: |
            ./dist/*.exe
            ./dist/*.exe.blockmap
            ./dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: echo "ğŸ This job's status is ${{ job.status }}."
